MVC/Controllers/ClubController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using MVC.Helpers;
using MVC.Interfaces;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers;

public class ClubController : Controller
{
    private readonly IClubRepository _clubRepository;
    private readonly IPhotoService _photoService;
    private readonly IHttpContextAccessor _httpContextAccessor;
    
    public ClubController(IClubRepository clubRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
    {
        _clubRepository = clubRepository;
        _photoService = photoService;
        _httpContextAccessor = httpContextAccessor;
    }

    // GET: Club
    public async Task<IActionResult> Index()
    {
        IEnumerable<Club> clubs = await _clubRepository.GetAll();
        return View(clubs);
    }

    //GET: Club/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }
        
        Club club = await _clubRepository.GetByIdAsync(id.Value);
        return View(club);
    }

    // GET: Club/Create
    public IActionResult Create()
    {
        string? currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
        if (currentUserId is null)
        {
            return RedirectToAction(nameof(Index));
        }

        var createClubViewModel = new CreateClubViewModel { AppUserId = currentUserId };
        return View(createClubViewModel);
    }
    
    // POST: Club/Create
    [HttpPost]
    public async Task<IActionResult> Create(CreateClubViewModel createClubViewModel)
    {
        if (ModelState.IsValid)
        {
            ImageUploadResult result = await _photoService.AddPhotoAsync(createClubViewModel.Image);
            
            var club = new Club
            {
                Title = createClubViewModel.Title,
                Description = createClubViewModel.Description,
                Image = result.Url.ToString(),
                ClubCategory = createClubViewModel.ClubCategory,
                AppUserId = createClubViewModel.AppUserId,
                Address = new Address
                {
                    State = createClubViewModel.Address.State,
                    City = createClubViewModel.Address.City,
                    Street = createClubViewModel.Address.Street
                }
            };
            await _clubRepository.AddAsync(club);
            return RedirectToAction(nameof(Index));
        }
        ModelState.AddModelError("", "Please fill all the required fields");
        return View(createClubViewModel);
    }
    
    // GET: Club/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Club club = await _clubRepository.GetByIdAsync(id.Value);
        
        var clubViewModel = new EditClubViewModel
        {
            Id = club.Id,
            Title = club.Title,
            Description = club.Description,
            Url = club.Image,
            ClubCategory = club.ClubCategory,
            AddressId = club.AddressId,
            Address = club.Address,
        };
        
        return View(clubViewModel);
    }
    
    // POST: Club/Edit/5
    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditClubViewModel editClubViewModel)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Failed to edit club due to invalid model state.");
            return View("Edit", editClubViewModel);
        }

        Club userClub = await _clubRepository.GetByIdAsync(id);

        if (editClubViewModel.Image != null)
        {
            ImageUploadResult photoResult = await _photoService.AddPhotoAsync(editClubViewModel.Image);
            if (photoResult.Error != null)
            {
                ModelState.AddModelError("Image", "Photo upload failed: " + photoResult.Error.Message);
                return View("Edit", editClubViewModel);
            }

            if (!string.IsNullOrEmpty(userClub.Image))
            {
                _ = _photoService.DeletePhotoAsync(userClub.Image);
            }

            userClub.Image = photoResult.Url.ToString();
        }

        userClub.Title = editClubViewModel.Title;
        userClub.Description = editClubViewModel.Description;
        userClub.ClubCategory = editClubViewModel.ClubCategory;
        userClub.AddressId = editClubViewModel.AddressId;
        userClub.Address = editClubViewModel.Address;

        await _clubRepository.UpdateAsync(userClub);
        return RedirectToAction(nameof(Index));
    }
    
    // GET: Club/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Club club = await _clubRepository.GetByIdAsync(id.Value);
        return View(club);
    }

    // POST: Club/Delete/5
    [HttpPost, ActionName("DeleteClub")]
    public async Task<IActionResult> DeleteClub(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Club club = await _clubRepository.GetByIdAsync(id.Value);
        
        await _clubRepository.DeleteAsync(club);
        return RedirectToAction(nameof(Index));
    }
}

MVC/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Interfaces;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers;

public class DashboardController : Controller
{
    private readonly IDashboardRepository _dashboardRepository;
    
    public DashboardController(IDashboardRepository dashboardRepository)
    {
        _dashboardRepository = dashboardRepository;
    }
    
    // GET: Dashboard
    public async Task<IActionResult> Index()
    {
        List<Race> userRaces = await _dashboardRepository.GetAllUserRacesAsync();
        List<Club> userClubs = await _dashboardRepository.GetAllUserClubsAsync();

        var dashboardViewModel = new DashboardViewModal
        {
            Races = userRaces,
            Clubs = userClubs
        };
        
        return View(dashboardViewModel);
    }
}

MVC/Controllers/RaceController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using MVC.Helpers;
using MVC.Interfaces;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers;
public class RaceController : Controller
{
    private readonly IRaceRepository _raceRepository;
    private readonly IPhotoService _photoService;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public RaceController(IRaceRepository raceRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
    {
        _raceRepository = raceRepository;
        _photoService = photoService;
        _httpContextAccessor = httpContextAccessor;
    }

    // GET: Race
    public async Task<IActionResult> Index()
    {
        IEnumerable<Race> races = await _raceRepository.GetAll();
        return View(races);
    }

    // GET: Race/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Race race = await _raceRepository.GetByIdAsync(id.Value);
        return View(race);
    }

    // GET: Race/Create
    public IActionResult Create()
    {
        string? currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
        if (currentUserId is null)
        {
            return RedirectToAction(nameof(Index));
        }
        
        var createRaceViewModel = new CreateRaceViewModel{ AppUserId = currentUserId };
        return View(createRaceViewModel);
    }

    // POST: Race/Create
    [HttpPost]
    public async Task<IActionResult> Create(CreateRaceViewModel createRaceViewModel)
    {
        if (ModelState.IsValid)
        {
            ImageUploadResult result = await _photoService.AddPhotoAsync(createRaceViewModel.Image);
            
            var race = new Race
            {
                Title = createRaceViewModel.Title,
                Description = createRaceViewModel.Description,
                Image = result.Url.ToString(),
                RaceCategory = createRaceViewModel.RaceCategory,
                AppUserId = createRaceViewModel.AppUserId,
                Address = new Address
                {
                    State = createRaceViewModel.Address.State,
                    City = createRaceViewModel.Address.City,
                    Street = createRaceViewModel.Address.Street
                }
            };
            await _raceRepository.AddAsync(race);
            return RedirectToAction(nameof(Index));
        }
        ModelState.AddModelError("", "Please fill all the required fields");
        return View(createRaceViewModel);
    }

    // GET: Race/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Race race = await _raceRepository.GetByIdAsync(id.Value);
        
        var raceVm = new EditRaceViewModel
        {
            Id = race.Id,
            Title = race.Title,
            Description = race.Description,
            Url = race.Image,
            RaceCategory = race.RaceCategory,
            AddressId = race.AddressId,
            Address = race.Address,
        };
        
        return View(raceVm);
    }
    
    // POST: Club/Edit/5
    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditRaceViewModel raceVm)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Failed to edit club due to invalid model state.");
            return View("Edit", raceVm);
        }

        Race userRace = await _raceRepository.GetByIdAsync(id);

        if (raceVm.Image != null)
        {
            ImageUploadResult photoResult = await _photoService.AddPhotoAsync(raceVm.Image);
            if (photoResult.Error != null)
            {
                ModelState.AddModelError("Image", "Photo upload failed: " + photoResult.Error.Message);
                return View("Edit", raceVm);
            }

            if (!string.IsNullOrEmpty(userRace.Image))
            {
                _ = _photoService.DeletePhotoAsync(userRace.Image);
            }

            userRace.Image = photoResult.Url.ToString();
        }

        userRace.Title = raceVm.Title;
        userRace.Description = raceVm.Description;
        userRace.RaceCategory = raceVm.RaceCategory;
        userRace.AddressId = raceVm.AddressId;
        userRace.Address = raceVm.Address;

        await _raceRepository.UpdateAsync(userRace);
        return RedirectToAction(nameof(Index));
    }

    // GET: Race/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Race race = await _raceRepository.GetByIdAsync(id.Value);
        return View(race);
    }

    // POST: Race/Delete/5
    [HttpPost, ActionName("DeleteRace")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Race race = await _raceRepository.GetByIdAsync(id.Value);
        await _raceRepository.DeleteAsync(race);
        return RedirectToAction(nameof(Index));
    }
}

MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Interfaces;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers;

[Route("users")]
public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    
    public UserController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }
    
    // GET: /users
    public async Task<IActionResult> Index()
    {
        IEnumerable<AppUser> users = await _userRepository.GetAllUsersAsync();
        List<UserViewModel> result = [];
        
        foreach (var user in users)
        {
            var userViewModel = new UserViewModel
            {
                Id = user.Id,
                Username = user.UserName ?? string.Empty,
                Pace = user.Pace ?? 0,
                Mileage = user.Mileage ?? 0
            };
            result.Add(userViewModel);
        }
        return View(result);
    }
    
    // GET: /users/{id}
    [HttpGet("{id}")]
    public async Task<IActionResult> Details(string id)
    {
        AppUser user = await _userRepository.GetUserByIdAsync(id);
        var userViewModel = new UserViewModel
        {
            Id = user.Id,
            Username = user.UserName ?? string.Empty,
            Pace = user.Pace ?? 0,
            Mileage = user.Mileage ?? 0
        };
        return View(userViewModel);
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity is { IsAuthenticated: true })
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Runners</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Index">Clubs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Race" asp-action="Index">Races</a>
                    </li>
                    @if (User.Identity is { IsAuthenticated: true })
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-danger" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>